import type { Metadata } from 'next';
import Link from 'next/link';


export const metadata: Metadata = {
  title: 'Exercícios 2',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    // Fundo Estático
    <div className="w-screen h-screen bg-gradient-to-r from-sky-800 to-gray-900 flex flex-col">
      {/* Container central */}
      <div className="container mx-auto w-2/3 flex-grow flex flex-col">
        {/* Conteúdo principal */}
        <div className="flex-grow flex flex-col justify-center items-center text-center mb-8">
          <h1 className="text-white text-2xl font-bold mb-4">Exercício 5</h1>
          <p className="text-white mb-4">Animação de Loading</p>
          <div className="w-12 h-12 border-8 border-blue-200 border-r-blue-600 border-t-blue-600 rounded-full animate-spin"></div>
        </div>

        {/* Pages Interaction */}
        <div className="mt-auto text-center">
          <Link href="/" className="underline text-white">
            Página 1
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Page;
